# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 28, 19, 1, 15, 399000), verbose_name='Date'),
        ),
    ]
