# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_auto_20170630_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 1, 0, 44, 59, 482000), verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
