# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_auto_20170701_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 18, 34, 12, 53000), verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
