# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_auto_20170707_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 18, 47, 12, 363000), verbose_name='Date'),
        ),
    ]
