# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0011_auto_20170707_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', through='collab.Collab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='matches',
            field=models.ManyToManyField(related_name='matches', through='collab.Match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 19, 28, 6, 866000), verbose_name='Date'),
        ),
    ]
