# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_auto_20170707_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.TimeField(default=datetime.datetime(2017, 7, 8, 0, 11, 33, 289000, tzinfo=utc), verbose_name='Date'),
        ),
    ]
