# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0014_auto_20170707_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(),
        ),
    ]
