# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0015_auto_20170707_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 0, 23, 18, 178000, tzinfo=utc), verbose_name='Date'),
        ),
    ]
