# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0018_remove_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 20, 32, 40, 194000), verbose_name='Date'),
        ),
    ]
