# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0019_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 11, 8, 11, 601000), verbose_name='Date'),
        ),
    ]
