# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0023_auto_20170708_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='project',
        ),
        migrations.RemoveField(
            model_name='request',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sender',
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 18, 52, 5, 985000), verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
