# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0024_auto_20170708_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 18, 59, 11, 872000), verbose_name='Date'),
        ),
    ]
