# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0036_auto_20170709_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 22, 43, 33, 441000), verbose_name='Date'),
        ),
    ]
