# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0038_auto_20170710_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 23, 36, 28, 578000), verbose_name='Date'),
        ),
    ]
