# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0040_auto_20170710_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 23, 58, 12, 111000), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_needed',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of skills', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Skills Needed'),
        ),
    ]
