# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0041_auto_20170710_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 12, 40, 1, 627000), verbose_name='Date'),
        ),
    ]
