# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0043_auto_20170711_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default='Philadelphia', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 14, 10, 41, 285000), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
