# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0049_auto_20170711_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Platform')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 15, 3, 28, 311000), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='socialproj',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Project'),
        ),
    ]
