# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0050_auto_20170711_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 23, 2, 44, 309000), verbose_name='Date'),
        ),
    ]
