# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0051_auto_20170711_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 23, 23, 59, 229000), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='socialproj',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collab.Platform'),
        ),
        migrations.AlterField(
            model_name='socialproj',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
