# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0052_auto_20170711_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 11, 24, 51, 227000), verbose_name='Date'),
        ),
    ]
