# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0053_auto_20170712_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 11, 42, 52, 665000), verbose_name='Date'),
        ),
    ]
