# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0054_auto_20170712_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 12, 7, 1, 506000), verbose_name='Date'),
        ),
    ]
