# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170712_2002'),
        ('collab', '0055_auto_20170712_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 20, 2, 24, 673000), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='socialproj',
            name='platform',
            field=models.CharField(choices=[('ps', 'Website'), ('gh', 'GitHub'), ('li', 'LinkedIn'), ('tw', 'Twitter'), ('tl', 'Trello'), ('fb', 'Facebook')], default='gh', max_length=2),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
