# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0060_auto_20170713_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 1, 23, 38, 339000), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='socialproj',
            name='platform',
            field=models.CharField(choices=[('ps', 'Website'), ('gh', 'fa fa-github fa-2x'), ('li', 'fa fa-linkedin fa-2x'), ('tw', 'fa fa-twitter fa-2x'), ('tl', 'fa fa-trello fa-2x'), ('fb', 'fa fa-facebook fa-2x')], default='gh', max_length=2),
        ),
    ]
