# Generated by Django 3.2.5 on 2021-10-12 20:43

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ps', 'fa fa-globe fa-3x'), ('gh', 'fa fa-github fa-3x'), ('li', 'fa fa-linkedin fa-3x'), ('tw', 'fa fa-twitter fa-3x'), ('tl', 'fa fa-trello fa-3x'), ('fb', 'fa fa-facebook-square fa-3x'), ('ig', 'fa fa-instagram fa-3x'), ('yt', 'fa fa-youtube fa-3x')], default='ps', max_length=2)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=15)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('experience', models.TextField(blank=True, max_length=500)),
                ('availability', models.TextField(blank=True, max_length=500)),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of skills', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Skills')),
            ],
        ),
    ]
