# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collab', '0008_auto_20170701_0044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('picture', models.ImageField(blank=True, upload_to=b'')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('experience', models.CharField(blank=True, max_length=500)),
                ('availability', models.CharField(blank=True, max_length=500)),
                ('technologies', models.ManyToManyField(blank=True, to='collab.Technology')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
