# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_request_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
