# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170708_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip',
            field=models.CharField(default=19128, max_length=15),
            preserve_default=False,
        ),
    ]
