# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:50
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('accounts', '0006_auto_20170709_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
