# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:58
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of skills', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
