# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170711_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='SocialUser',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Platform'),
        ),
    ]
