# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170711_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='socialuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialUser',
        ),
    ]
