# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0050_auto_20170711_1503'),
        ('accounts', '0011_auto_20170711_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collab.Platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
