# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collab.Platform'),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
