# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170712_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='platform',
            field=models.CharField(choices=[('ps', 'Website'), ('gh', 'GitHub'), ('li', 'LinkedIn'), ('tw', 'Twitter'), ('tl', 'Trello'), ('fb', 'Facebook')], default='ps', max_length=2),
        ),
    ]
