# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170712_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='platform',
            field=models.CharField(choices=[('ps', 'Website'), ('gh', 'fa fa-github fa-2x'), ('li', 'fa fa-linkedin fa-2x'), ('tw', 'fa fa-twitter fa-2x'), ('tl', 'fa fa-trello fa-2x'), ('fb', 'fa fa-facebook fa-2x')], default='ps', max_length=2),
        ),
    ]
